name: "MiNiFi-CPP CI"
on: [push, pull_request, workflow_dispatch]
jobs:
  macos_xcode_12_0:
    name: "macos-xcode12.0"
    runs-on: macos-10.15
    timeout-minutes: 90
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: setup_env
        name: setup enviroment
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: build
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: test
        run: build/main
  windows_VS2019:
    name: "windows-vs2019"
    runs-on: windows-2019
    timeout-minutes: 180
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - name: Setup PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: list
        run: |
          C:
          cd C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools
          dir
        shell: cmd
      - name: build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          msbuild /m regex.sln /property:Configuration=RelWithDebInfo /property:Platform=x64
          dir
        shell: cmd
      - name: test
        run: |
          cd build
          dir
          cd RelWithDebInfo
          dir
        shell: cmd
